# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackathonxp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hackathonxp

  target 'hackathonxpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hackathonxpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
